version: '3.1'

services:
   postgres:
      restart: always
      image: postgres:9.6.3
      ports:
        - "5432:5432"
      env_file: images/postgres/.postgres.env
   
   gitrob:
      restart: always
      build: ./images/gitrob
      image: gitrob:1.0
      ports:
        - "9393:9393"
      links:
        - postgres:postgres
      env_file: images/gitrob/.gitrob.env
      entrypoint: ["/rootfs/gitrob_init.sh"]
